CREATE TABLE cars (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    model VARCHAR(30) NOT NULL,
    year_of_issue INTEGER NOT NULL,
    mileage INTEGER NOT NULL,
    body_type VARCHAR(20) NOT NULL,
    color VARCHAR(10) NOT NULL,
    engine_size DOUBLE PRECISION NOT NULL,
    horse_power INTEGER NOT NULL,
    transmission_type VARCHAR(10) NOT NULL,
    drive_type VARCHAR(5) NOT NULL,
    vin VARCHAR(20) NOT NULL UNIQUE
);